apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-example
  annotations:
    kube-restarter.io/enabled: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-example
  template:
    metadata:
      labels:
        app: nginx-example
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
